[project]
name = "spotify-web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "librosa>=0.11.0",
    "matplotlib>=3.10.8",
    "spotipy>=2.25.2",
]

[tool.uv.workspace]
members = [
    "backend",
]
